services:
  bitcoin-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bitcoin_tracker
    env_file: .env
    volumes:
      - .:/app
    restart: "no"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: bitcoin_tracker_api
    env_file: .env
    ports:
      - "8000:8000"
    restart: always
