name: Run BTC Tracker with Allure Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Create Local Directories for Mounting
        run: |
          mkdir -p ./output ./allure-results

      - name: Build Docker Image Locally
        run: |
          docker build -t bitcoin-tracker:local -f Dockerfile .

      - name: Run Docker Container Locally
        run: |
          docker run --rm \
            -e SMTP_HOST=${{ secrets.SMTP_HOST }} \
            -e SMTP_PORT=${{ secrets.SMTP_PORT }} \
            -e SENDER_EMAIL=${{ secrets.SENDER_EMAIL }} \
            -e SENDER_PASSWORD=${{ secrets.SENDER_PASSWORD }} \
            -e RECIPIENT_EMAIL=${{ secrets.RECIPIENT_EMAIL }} \
            -e API_URL=${{ secrets.API_URL }} \
            -e OUTPUT_FILE=/app/output/price.json \
            -v ${{ github.workspace }}/output:/app/output \
            -v ${{ github.workspace }}/allure-results:/app/allure-results \
            bitcoin-tracker:local

      - name: Debug Allure Results Folder
        run: |
          echo "Checking allure-results contents..."
          ls -la ./allure-results || echo "No allure-results found"

      - name: Install Java (for Allure CLI)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -zxvf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Generate Allure Report
        run: |
          rm -rf ./allure-report
          mkdir -p ./allure-report
          allure generate ./allure-results --clean -o ./allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
